-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Event" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Shot" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Target" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TargetType" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TargetTypeRing" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UserCourseRecord" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UserShot" ALTER COLUMN "dateCreated" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "dateUpdated" SET DEFAULT CURRENT_TIMESTAMP;
